### ISSUE TITLE
broken built 

### ISSUE THREAD

**Issue by tarunkapadia93** [NamelessRom/android_external_sepolicy#1]
https://github.com/NamelessRom/android_external_sepolicy/commit/ad106e774f6a282254015120c56ab5da53f9c2b1 

this is breaking the build for me sir 

tried to revert it and it worked flawlessly

**Comment by amartinz** [comment]
we take code contributions only via https://gerrit.nameless-rom.org

the build is not broken for any device we support, fix your device specific sepolicy instead :)
